modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="apothic_enchanting"

version="2.1.0"

displayName="Apothic Enchanting"

authors="Shadows_of_Fire"

description='''The Enchanting Module of Apotheosis, overhauling major enchanting systems.'''

[[mixins]]
config="apothic_enchanting.mixins.json"

[[dependencies.apothic_enchanting]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apothic_enchanting]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.64-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apothic_enchanting]]
    modId="placebo"
    type="required"
    versionRange="[10.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.apothic_enchanting]]
    modId="apothic_attributes"
    type="required"
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"
